/// Flutter icons DTypeTracking
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DTypeTracking
///      fonts:
///       - asset: fonts/DTypeTracking.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class DTypeTracking {
  DTypeTracking._();

  static const _kFontFam = 'DTypeTracking';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData water = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData blood = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xf0f5, fontFamily: _kFontFam);
}
